const applicationsData = [
  {
    id: "amazon-sde-intern",
    company: "Amazon",
    role: "SDE Intern",
    status: "Interview",
    avatarBg: "bg-white",
    avatarText: "text-black",
    avatarLetter: "a",
    appliedDate: "2026-05-20",
    expectedCTC: "₹12 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "1234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Technical Interview", date: "2026-08-22", time: "10:00 AM", badge: "In 2 days" },
    notes: "Prepare DSA + System Design.\nFocus on problem solving speed.",
    timeline: [
      { id: 1, stage: "Applied", date: "20 May", completed: true },
      { id: 2, stage: "OA", date: "23 May", completed: true },
      { id: 3, stage: "Interview", date: "22 Aug", completed: false, current: true },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [
      { id: 1, label: "Resume (PDF)", url: "#" },
      { id: 2, label: "Cover Letter", url: "#" },
    ],
  },
  {
    id: "microsoft-sde-intern",
    company: "Microsoft",
    role: "SDE Intern",
    status: "OA",
    avatarBg: "bg-white",
    avatarText: "text-blue-600",
    avatarLetter: "M",
    appliedDate: "2026-05-18",
    expectedCTC: "₹15 LPA",
    jobType: "Internship",
    location: "Hyderabad",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "2234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Online Assessment", date: "2026-08-21", time: "6:00 PM", badge: "In 1 day" },
    notes: "Revise arrays, strings and basic DP before the OA.",
    timeline: [
      { id: 1, stage: "Applied", date: "18 May", completed: true },
      { id: 2, stage: "OA", date: "21 Aug", completed: false, current: true },
      { id: 3, stage: "Interview", date: null, completed: false },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "google-step-intern",
    company: "Google",
    role: "STEP Intern",
    status: "Applied",
    avatarBg: "bg-white",
    avatarText: "text-red-500",
    avatarLetter: "G",
    appliedDate: "2026-05-15",
    expectedCTC: "₹18 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "Engineering",
    experience: "Fresher",
    batch: "2026",
    jobId: "3234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Online Assessment", date: null, time: null, badge: "TBD" },
    notes: "Waiting to hear back on OA scheduling.",
    timeline: [
      { id: 1, stage: "Applied", date: "15 May", completed: true },
      { id: 2, stage: "OA", date: null, completed: false },
      { id: 3, stage: "Interview", date: null, completed: false },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "adobe-sde-intern",
    company: "Adobe",
    role: "SDE Intern",
    status: "Interview",
    avatarBg: "bg-red-600",
    avatarText: "text-white",
    avatarLetter: "A",
    appliedDate: "2026-05-12",
    expectedCTC: "₹14 LPA",
    jobType: "Internship",
    location: "Noida",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "4234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "HR Round", date: "2026-08-25", time: "3:00 PM", badge: "In 5 days" },
    notes: "Cleared technical rounds — prepare behavioral answers.",
    timeline: [
      { id: 1, stage: "Applied", date: "12 May", completed: true },
      { id: 2, stage: "OA", date: "15 May", completed: true },
      { id: 3, stage: "Interview", date: "25 Aug", completed: false, current: true },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [
      { id: 1, label: "Resume (PDF)", url: "#" },
      { id: 2, label: "Portfolio Link", url: "#" },
    ],
  },
  {
    id: "flipkart-sde-intern",
    company: "Flipkart",
    role: "SDE Intern",
    status: "OA",
    avatarBg: "bg-yellow-400",
    avatarText: "text-blue-900",
    avatarLetter: "F",
    appliedDate: "2026-05-10",
    expectedCTC: "₹13 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "5234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Coding Assessment", date: "2026-08-20", time: "7:00 PM", badge: "Tomorrow" },
    notes: "Focus on SQL and array problems for the OA.",
    timeline: [
      { id: 1, stage: "Applied", date: "10 May", completed: true },
      { id: 2, stage: "OA", date: "20 Aug", completed: false, current: true },
      { id: 3, stage: "Interview", date: null, completed: false },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "atlassian-sde-intern",
    company: "Atlassian",
    role: "SDE Intern",
    status: "Offer",
    avatarBg: "bg-blue-600",
    avatarText: "text-white",
    avatarLetter: "AT",
    appliedDate: "2026-04-28",
    expectedCTC: "₹20 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "6234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Offer accepted", date: null, time: null, badge: "Completed" },
    notes: "Accepted the offer — respond to onboarding email.",
    timeline: [
      { id: 1, stage: "Applied", date: "28 Apr", completed: true },
      { id: 2, stage: "OA", date: "2 May", completed: true },
      { id: 3, stage: "Interview", date: "10 May", completed: true },
      { id: 4, stage: "Offer", date: "18 May", completed: true },
    ],
    resources: [{ id: 1, label: "Offer Letter", url: "#" }],
  },
  {
    id: "swiggy-sde-intern",
    company: "Swiggy",
    role: "Backend Intern",
    status: "Rejected",
    avatarBg: "bg-orange-500",
    avatarText: "text-white",
    avatarLetter: "S",
    appliedDate: "2026-04-15",
    expectedCTC: "₹11 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "Backend",
    experience: "Fresher",
    batch: "2026",
    jobId: "7234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Process closed", date: null, time: null, badge: "Rejected" },
    notes: "Rejected after technical round — review system design basics.",
    timeline: [
      { id: 1, stage: "Applied", date: "15 Apr", completed: true },
      { id: 2, stage: "OA", date: "18 Apr", completed: true },
      { id: 3, stage: "Interview", date: "25 Apr", completed: true },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "zomato-sde-intern",
    company: "Zomato",
    role: "SDE Intern",
    status: "Applied",
    avatarBg: "bg-red-500",
    avatarText: "text-white",
    avatarLetter: "Z",
    appliedDate: "2026-05-22",
    expectedCTC: "₹10 LPA",
    jobType: "Internship",
    location: "Gurugram",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "8234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Awaiting response", date: null, time: null, badge: "TBD" },
    notes: "",
    timeline: [{ id: 1, stage: "Applied", date: "22 May", completed: true }],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "paypal-sde-intern",
    company: "PayPal",
    role: "SDE Intern",
    status: "Rejected",
    avatarBg: "bg-blue-800",
    avatarText: "text-white",
    avatarLetter: "P",
    appliedDate: "2026-04-05",
    expectedCTC: "₹16 LPA",
    jobType: "Internship",
    location: "Chennai",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "9234567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Process closed", date: null, time: null, badge: "Rejected" },
    notes: "Did not clear the OA — retry next cycle.",
    timeline: [{ id: 1, stage: "Applied", date: "5 Apr", completed: true }, { id: 2, stage: "OA", date: "8 Apr", completed: true }],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "cisco-sde-intern",
    company: "Cisco",
    role: "SDE Intern",
    status: "Applied",
    avatarBg: "bg-cyan-600",
    avatarText: "text-white",
    avatarLetter: "C",
    appliedDate: "2026-05-25",
    expectedCTC: "₹13 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "1034567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Awaiting response", date: null, time: null, badge: "TBD" },
    notes: "",
    timeline: [{ id: 1, stage: "Applied", date: "25 May", completed: true }],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "walmart-sde-intern",
    company: "Walmart Labs",
    role: "SDE Intern",
    status: "Interview",
    avatarBg: "bg-blue-500",
    avatarText: "text-white",
    avatarLetter: "W",
    appliedDate: "2026-05-08",
    expectedCTC: "₹17 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "1134567",
    jobDescriptionUrl: "#",
    nextStep: { title: "System Design Round", date: "2026-08-24", time: "11:00 AM", badge: "In 4 days" },
    notes: "Review scalability patterns before the round.",
    timeline: [
      { id: 1, stage: "Applied", date: "8 May", completed: true },
      { id: 2, stage: "OA", date: "12 May", completed: true },
      { id: 3, stage: "Interview", date: "24 Aug", completed: false, current: true },
      { id: 4, stage: "Offer", date: null, completed: false },
    ],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "razorpay-sde-intern",
    company: "Razorpay",
    role: "SDE Intern",
    status: "Rejected",
    avatarBg: "bg-blue-700",
    avatarText: "text-white",
    avatarLetter: "R",
    appliedDate: "2026-03-20",
    expectedCTC: "₹12 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "1234568",
    jobDescriptionUrl: "#",
    nextStep: { title: "Process closed", date: null, time: null, badge: "Rejected" },
    notes: "",
    timeline: [{ id: 1, stage: "Applied", date: "20 Mar", completed: true }],
    resources: [{ id: 1, label: "Resume (PDF)", url: "#" }],
  },
  {
    id: "uber-sde-intern",
    company: "Uber",
    role: "SDE Intern",
    status: "Offer",
    avatarBg: "bg-black",
    avatarText: "text-white",
    avatarLetter: "U",
    appliedDate: "2026-04-01",
    expectedCTC: "₹19 LPA",
    jobType: "Internship",
    location: "Bengaluru",
    department: "SDE",
    experience: "Fresher",
    batch: "2026",
    jobId: "1334567",
    jobDescriptionUrl: "#",
    nextStep: { title: "Offer accepted", date: null, time: null, badge: "Completed" },
    notes: "Backup offer — decision pending against Atlassian.",
    timeline: [
      { id: 1, stage: "Applied", date: "1 Apr", completed: true },
      { id: 2, stage: "OA", date: "5 Apr", completed: true },
      { id: 3, stage: "Interview", date: "15 Apr", completed: true },
      { id: 4, stage: "Offer", date: "25 Apr", completed: true },
    ],
    resources: [{ id: 1, label: "Offer Letter", url: "#" }],
  },
];

export default applicationsData;