const contestsData = [
  // Upcoming
  {
    id: "cf-950",
    name: "Codeforces Round #950 (Div. 2)",
    platform: "Codeforces",
    status: "Upcoming",
    type: "Rated",
    date: "2026-08-20",
    startTime: "8:30 PM IST",
    duration: "2h 15m",
    startsIn: "In 2d 4h",
    registrationLink: "https://codeforces.com/contests",
  },
  {
    id: "lc-w429",
    name: "LeetCode Weekly Contest 429",
    platform: "LeetCode",
    status: "Upcoming",
    type: "Rated",
    date: "2026-08-22",
    startTime: "8:00 AM IST",
    duration: "1h 30m",
    startsIn: "In 4d",
    registrationLink: "https://leetcode.com/contest",
  },
  {
    id: "cc-113",
    name: "CodeChef Starters 113",
    platform: "CodeChef",
    status: "Upcoming",
    type: "Rated",
    date: "2026-08-24",
    startTime: "9:30 PM IST",
    duration: "2h",
    startsIn: "In 6d",
    registrationLink: "https://www.codechef.com/contests",
  },

  // History (Participated)
  {
    id: "cf-949",
    name: "Codeforces Round #949 (Div. 2)",
    platform: "Codeforces",
    status: "Participated",
    type: "Rated",
    date: "2026-08-13",
    startTime: "8:30 PM IST",
    duration: "2h 15m",
    registrationLink: "https://codeforces.com/contest/949",
    rank: 563,
    totalParticipants: 12345,
    ratingChange: 42,
    score: 742,
    solved: 5,
    totalProblems: 8,
    penalty: 2,
    percentage: 72.45,
    notes: "Good contest. Need to improve on graphs and advanced data structures.",
    problems: [
      { id: "A", name: "Add Odd or Subtract Even", points: 500, solved: true },
      { id: "B", name: "Divide and Multiply", points: 1000, solved: true },
      { id: "C", name: "XOR Reconstruction", points: 1500, solved: true },
      { id: "D", name: "Tree and Queries", points: 2000, solved: true },
      { id: "E", name: "Permutation Game", points: 2400, solved: false },
      { id: "F", name: "Maximum Flow", points: 2800, solved: false },
      { id: "G", name: "Hard Problem", points: 3200, solved: false },
      { id: "H", name: "Extra Hard Problem", points: 3600, solved: false },
    ],
  },
  {
    id: "lc-428",
    name: "LeetCode Weekly Contest 428",
    platform: "LeetCode",
    status: "Participated",
    type: "Rated",
    date: "2026-08-15",
    startTime: "8:00 AM IST",
    duration: "1h 30m",
    registrationLink: "https://leetcode.com/contest/weekly-contest-428",
    rank: 842,
    totalParticipants: 9800,
    ratingChange: 18,
    score: 620,
    solved: 4,
    totalProblems: 5,
    penalty: 1,
    percentage: 80,
    notes: "Missed the last problem due to a TLE — need to optimize sooner.",
    problems: [
      { id: "1", name: "Two Sum Variant", points: 100, solved: true },
      { id: "2", name: "Sliding Window Max", points: 200, solved: true },
      { id: "3", name: "Graph Coloring", points: 400, solved: true },
      { id: "4", name: "DP on Trees", points: 600, solved: true },
      { id: "5", name: "Hard Optimization", points: 800, solved: false },
    ],
  },
  {
    id: "cf-948",
    name: "Codeforces Round #948 (Div. 3)",
    platform: "Codeforces",
    status: "Participated",
    type: "Rated",
    date: "2026-08-06",
    startTime: "8:30 PM IST",
    duration: "2h 15m",
    registrationLink: "https://codeforces.com/contest/948",
    rank: 721,
    totalParticipants: 15200,
    ratingChange: 25,
    score: 610,
    solved: 4,
    totalProblems: 7,
    penalty: 3,
    percentage: 57.14,
    notes: "Solid performance, ran out of time on problem F.",
    problems: [
      { id: "A", name: "Simple Sum", points: 500, solved: true },
      { id: "B", name: "Array Rotation", points: 750, solved: true },
      { id: "C", name: "String Matching", points: 1000, solved: true },
      { id: "D", name: "Binary Search Tree", points: 1250, solved: true },
      { id: "E", name: "Segment Tree Query", points: 1750, solved: false },
      { id: "F", name: "Graph Shortest Path", points: 2000, solved: false },
      { id: "G", name: "Advanced DP", points: 2500, solved: false },
    ],
  },
  {
    id: "lc-bw133",
    name: "LeetCode Biweekly Contest 133",
    platform: "LeetCode",
    status: "Participated",
    type: "Rated",
    date: "2026-08-01",
    startTime: "8:00 PM IST",
    duration: "1h 30m",
    registrationLink: "https://leetcode.com/contest/biweekly-contest-133",
    rank: 1052,
    totalParticipants: 8700,
    ratingChange: 12,
    score: 480,
    solved: 3,
    totalProblems: 6,
    penalty: 2,
    percentage: 50,
    notes: "Struggled with the DP problem — needs more practice.",
    problems: [
      { id: "1", name: "Basic Array", points: 100, solved: true },
      { id: "2", name: "String Parsing", points: 200, solved: true },
      { id: "3", name: "Two Pointers", points: 400, solved: true },
      { id: "4", name: "DP Optimization", points: 600, solved: false },
      { id: "5", name: "Graph Cycle", points: 800, solved: false },
      { id: "6", name: "Hard Constructive", points: 1000, solved: false },
    ],
  },
  {
    id: "cc-112",
    name: "CodeChef Starters 112",
    platform: "CodeChef",
    status: "Participated",
    type: "Rated",
    date: "2026-07-27",
    startTime: "9:30 PM IST",
    duration: "2h",
    registrationLink: "https://www.codechef.com/START112",
    rank: 1340,
    totalParticipants: 6400,
    ratingChange: 0,
    score: 300,
    solved: 2,
    totalProblems: 4,
    penalty: 0,
    percentage: 50,
    notes: "Rating unchanged — need to attempt harder problems for better gains.",
    problems: [
      { id: "1", name: "Chef and Sum", points: 100, solved: true },
      { id: "2", name: "Array Balance", points: 150, solved: true },
      { id: "3", name: "Chef and Graphs", points: 200, solved: false },
      { id: "4", name: "Hard Query", points: 250, solved: false },
    ],
  },
];

export default contestsData;