import { SiLeetcode, SiGeeksforgeeks } from "react-icons/si";

const dsaProblems = [
  {
    id: 1,
    name: "Two Sum",
    difficulty: "Easy",
    topic: "Arrays",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Solved",
    lastSolved: "Today",
    lastRevision: "Today",
    favourite: true,
  },
  {
    id: 2,
    name: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topic: "Linked List",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Solved",
    lastSolved: "Yesterday",
    lastRevision: "2 days ago",
    favourite: true,
  },
  {
    id: 3,
    name: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    topic: "Sliding Window",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Solved",
    lastSolved: "2 Aug 2026",
    lastRevision: "5 days ago",
    favourite: false,
  },
  {
    id: 4,
    name: "Word Ladder",
    difficulty: "Hard",
    topic: "BFS",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Attempted",
    lastSolved: "1 Aug 2026",
    lastRevision: "1 Aug 2026",
    favourite: false,
  },
  {
    id: 5,
    name: "Maximum Subarray",
    difficulty: "Medium",
    topic: "DP",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Solved",
    lastSolved: "1 Aug 2026",
    lastRevision: "3 days ago",
    favourite: true,
  },
  {
    id: 6,
    name: "LRU Cache",
    difficulty: "Hard",
    topic: "Design",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Solved",
    lastSolved: "31 Jul 2026",
    lastRevision: "6 days ago",
    favourite: true,
  },
  {
    id: 7,
    name: "Reverse Linked List",
    difficulty: "Easy",
    topic: "Linked List",
    platform: "GeeksforGeeks",
    platformIcon: SiGeeksforgeeks,
    platformColor: "text-emerald-500",
    status: "Solved",
    lastSolved: "31 Jul 2026",
    lastRevision: "10 days ago",
    favourite: false,
  },
  {
    id: 8,
    name: "Number of Islands",
    difficulty: "Medium",
    topic: "DFS",
    platform: "LeetCode",
    platformIcon: SiLeetcode,
    platformColor: "text-amber-500",
    status: "Attempted",
    lastSolved: "30 Jul 2026",
    lastRevision: "30 Jul 2026",
    favourite: false,
  },
];

export default dsaProblems;
