import { FaBriefcase, FaCode, FaBookOpen, FaRocket, FaUserTie, FaReact, FaJs } from "react-icons/fa";

// Two "shapes" of goal exist:
// - "milestones": progress = completed checklist items / total
// - "counter": progress = current / target (e.g. 320 / 500 problems)
const goalsData = [
  {
    id: "crack-10-lpa",
    title: "Crack 10 LPA Placement",
    description: "Become a software developer and get a 10 LPA package",
    icon: FaBriefcase,
    color: "text-violet-400",
    bg: "bg-violet-500/15",
    barColor: "linear-gradient(90deg,#8B5CF6,#A78BFA)",
    hex: "#8B5CF6",
    deadline: "2026-09-30",
    progressType: "milestones",
    unitLabel: "milestones completed",
    notes: "Focus on consistency. Daily progress will lead to big results. Believe in yourself and keep pushing!",
    milestones: [
      { id: 1, title: "Complete DSA Preparation", completed: true },
      { id: 2, title: "Complete DBMS + SQL", completed: true },
      { id: 3, title: "Complete Web Development", completed: true },
      { id: 4, title: "Build 2 Major Projects", completed: true },
      { id: 5, title: "Solve 500 LeetCode Problems", completed: false },
      { id: 6, title: "Complete Core Subjects", completed: false },
      { id: 7, title: "Give Mock Interviews", completed: false },
      { id: 8, title: "Apply to 30 Companies", completed: false },
      { id: 9, title: "Crack OA Rounds", completed: false },
      { id: 10, title: "Clear Technical Interviews", completed: false },
      { id: 11, title: "Clear HR Interviews", completed: false },
      { id: 12, title: "Get 10 LPA Offer", completed: false },
    ],
  },
  {
    id: "leetcode-500",
    title: "Solve 500 LeetCode Problems",
    description: "Improve problem solving skills by solving 500 LC problems",
    icon: FaCode,
    color: "text-green-400",
    bg: "bg-green-500/15",
    barColor: "linear-gradient(90deg,#22C55E,#4ADE80)",
    hex: "#22C55E",
    deadline: "2026-12-31",
    progressType: "counter",
    unitLabel: "problems solved",
    current: 320,
    target: 500,
    notes: "Aim for at least 2 problems a day to stay on pace before December.",
  },
  {
    id: "core-subjects",
    title: "Complete Core Subjects",
    description: "Complete all core computer science subjects",
    icon: FaBookOpen,
    color: "text-blue-400",
    bg: "bg-blue-500/15",
    barColor: "linear-gradient(90deg,#3B82F6,#60A5FA)",
    hex: "#3B82F6",
    deadline: "2026-09-30",
    progressType: "counter",
    unitLabel: "topics completed",
    current: 18,
    target: 30,
    notes: "Prioritize DBMS and OS since they come up most often in interviews.",
  },
  {
    id: "3-major-projects",
    title: "Build 3 Major Projects",
    description: "Build 3 end-to-end projects and deploy them",
    icon: FaRocket,
    color: "text-orange-400",
    bg: "bg-orange-500/15",
    barColor: "linear-gradient(90deg,#F97316,#FBBF24)",
    hex: "#F97316",
    deadline: "2026-10-31",
    progressType: "counter",
    unitLabel: "projects completed",
    current: 1,
    target: 3,
    notes: "Placement Progress Tracker counts as project #2 once deployed.",
  },
  {
    id: "ace-interviews",
    title: "Ace Placements Interviews",
    description: "Prepare for technical and HR interviews",
    icon: FaUserTie,
    color: "text-pink-400",
    bg: "bg-pink-500/15",
    barColor: "linear-gradient(90deg,#EC4899,#F472B6)",
    hex: "#EC4899",
    deadline: "2026-11-30",
    progressType: "counter",
    unitLabel: "mock interviews completed",
    current: 3,
    target: 10,
    notes: "Schedule at least one mock interview every week leading up to placements.",
  },
];

export const completedGoalsData = [
  {
    id: "react-portfolio",
    title: "Build React Portfolio",
    description: "Build and deploy a personal portfolio",
    icon: FaReact,
    color: "text-cyan-400",
    bg: "bg-cyan-500/15",
    completedDate: "2024-05-15",
  },
  {
    id: "js-course",
    title: "Complete JavaScript Course",
    description: "Finish advanced JavaScript course",
    icon: FaJs,
    color: "text-yellow-400",
    bg: "bg-yellow-500/15",
    completedDate: "2024-04-10",
  },
];

export default goalsData;