import { FaCode, FaHospital, FaDollarSign, FaHome, FaUserTie } from "react-icons/fa";

const projectsData = [
  {
    id: "progress-tracker",
    name: "Progress Tracker",
    description: "Personal productivity and placement preparation tracker.",
    icon: FaCode,
    color: "text-violet-400",
    bg: "bg-violet-500/15",
    barColor: "linear-gradient(90deg,#8B5CF6,#A78BFA)",
    hex: "#8B5CF6",
    status: "In Progress",
    technologies: ["React", "Tailwind CSS", "Vite", "Recharts", "React Router", "Local Storage"],
    repoUrl: "https://github.com/ritu-singh/Progress-Tracker",
    notes: "Building this project to track my preparation and stay consistent every day.",
    lastUpdated: "Updated today",
    tasks: [
      { id: 1, title: "Setup React + Vite", completed: true },
      { id: 2, title: "Create Dashboard", completed: true },
      { id: 3, title: "Daily Habits Page", completed: true },
      { id: 4, title: "DSA Tracker Page", completed: true },
      { id: 5, title: "Subjects Page", completed: true },
      { id: 6, title: "Goals Page", completed: true },
      { id: 7, title: "Applications Page", completed: true },
      { id: 8, title: "Profile Page", completed: true },
      { id: 9, title: "Projects Page", completed: false },
      { id: 10, title: "Settings Page", completed: false },
      { id: 11, title: "Backend Integration", completed: false },
      { id: 12, title: "Deployment", completed: false },
    ],
  },
  {
    id: "hospital-management",
    name: "Hospital Management System",
    description: "Hospital management system with patient, doctor and billing modules.",
    icon: FaHospital,
    color: "text-emerald-400",
    bg: "bg-emerald-500/15",
    barColor: "linear-gradient(90deg,#10B981,#34D399)",
    hex: "#10B981",
    status: "In Progress",
    technologies: ["Java", "Spring Boot", "MySQL"],
    repoUrl: "https://github.com/ritu-singh/Hospital-Management",
    notes: "Focus on the billing module next — patient and doctor modules are stable.",
    lastUpdated: "Updated 2 days ago",
    tasks: [
      { id: 1, title: "Patient Module", completed: true },
      { id: 2, title: "Doctor Module", completed: true },
      { id: 3, title: "Appointment Scheduling", completed: true },
      { id: 4, title: "Billing Module", completed: false },
      { id: 5, title: "Admin Dashboard", completed: false },
    ],
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Real-time currency converter with historical data.",
    icon: FaDollarSign,
    color: "text-amber-400",
    bg: "bg-amber-500/15",
    barColor: "linear-gradient(90deg,#F59E0B,#FBBF24)",
    hex: "#F59E0B",
    status: "Completed",
    technologies: ["React", "Tailwind CSS", "API"],
    repoUrl: "https://github.com/ritu-singh/Currency-Converter",
    notes: "Shipped and deployed. Consider adding a chart view for historical trends.",
    lastUpdated: "Updated 5 days ago",
    tasks: [
      { id: 1, title: "API Integration", completed: true },
      { id: 2, title: "Currency Selector UI", completed: true },
      { id: 3, title: "Historical Chart", completed: true },
      { id: 4, title: "Deploy", completed: true },
    ],
  },
  {
    id: "real-estate-website",
    name: "Real Estate Website",
    description: "Real estate listing website with search, filters and user dashboard.",
    icon: FaHome,
    color: "text-blue-400",
    bg: "bg-blue-500/15",
    barColor: "linear-gradient(90deg,#3B82F6,#60A5FA)",
    hex: "#3B82F6",
    status: "In Progress",
    technologies: ["React", "Redux Toolkit", "Tailwind CSS"],
    repoUrl: "https://github.com/ritu-singh/Real-Estate-Website",
    notes: "User dashboard and saved listings still need to be built.",
    lastUpdated: "Updated 1 week ago",
    tasks: [
      { id: 1, title: "Listing Grid", completed: true },
      { id: 2, title: "Search & Filters", completed: true },
      { id: 3, title: "Property Details Page", completed: false },
      { id: 4, title: "User Dashboard", completed: false },
    ],
  },
  {
    id: "portfolio-website",
    name: "Portfolio Website",
    description: "Personal portfolio website to showcase my projects and skills.",
    icon: FaUserTie,
    color: "text-purple-400",
    bg: "bg-purple-500/15",
    barColor: "linear-gradient(90deg,#A855F7,#C084FC)",
    hex: "#A855F7",
    status: "Planned",
    technologies: ["React", "Tailwind CSS", "Framer Motion"],
    repoUrl: "https://github.com/ritu-singh/Portfolio-Website",
    notes: "Wireframes are done — start once the Progress Tracker is deployed.",
    lastUpdated: "Not started yet",
    tasks: [
      { id: 1, title: "Wireframes", completed: true },
      { id: 2, title: "Hero Section", completed: false },
      { id: 3, title: "Projects Section", completed: false },
    ],
  },
];

export default projectsData;