import {
  FaDatabase,
  FaCogs,
  FaNetworkWired,
  FaCubes,
  FaLaptopCode,
  FaMicrochip,
} from "react-icons/fa";

// Each topic has BOTH a `completed` flag (manually checked off by the user)
// and a `progress` percentage (mastery level) — they're tracked separately,
// same as your DSA topic-progress model.
const subjectsData = [
  {
    id: "dbms",
    name: "DBMS",
    description: "Database Management Systems",
    icon: FaDatabase,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    barColor: "linear-gradient(90deg,#3B82F6,#60A5FA)",
    streak: 8,
    studyHours: 12.5,
    lastStudied: "Today",
    dailyTarget: "1 Topic / day",
    notes: "Focus on normalization forms and indexing strategies before the next mock interview.",
    resources: [
      { id: 1, label: "GeeksforGeeks - DBMS Tutorial", url: "https://www.geeksforgeeks.org/dbms/" },
      { id: 2, label: "YouTube - CodeHelp DBMS Playlist", url: "https://www.youtube.com" },
      { id: 3, label: "DBMS Notes (PDF)", url: "#" },
    ],
    topics: [
      { id: 1, name: "ER Model", completed: true, progress: 100 },
      { id: 2, name: "Relational Model", completed: true, progress: 100 },
      { id: 3, name: "SQL", completed: true, progress: 80 },
      { id: 4, name: "Keys", completed: true, progress: 70 },
      { id: 5, name: "Normalization", completed: false, progress: 40 },
      { id: 6, name: "Transactions", completed: false, progress: 35 },
      { id: 7, name: "Indexing", completed: false, progress: 50 },
      { id: 8, name: "ACID Properties", completed: false, progress: 20 },
    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    description: "Core OS Concepts",
    icon: FaCogs,
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    barColor: "linear-gradient(90deg,#F97316,#FBBF24)",
    streak: 5,
    studyHours: 15,
    lastStudied: "Yesterday",
    dailyTarget: "1 Topic / day",
    notes: "Revisit deadlock avoidance algorithms — came up in the last two interviews.",
    resources: [
      { id: 1, label: "GeeksforGeeks - OS Tutorial", url: "https://www.geeksforgeeks.org/operating-systems/" },
      { id: 2, label: "OS Notes (PDF)", url: "#" },
    ],
    topics: [
      { id: 1, name: "Process Management", completed: true, progress: 100 },
      { id: 2, name: "Threading", completed: true, progress: 90 },
      { id: 3, name: "CPU Scheduling", completed: true, progress: 85 },
      { id: 4, name: "Deadlock", completed: false, progress: 45 },
      { id: 5, name: "Memory Management", completed: false, progress: 30 },
      { id: 6, name: "Virtual Memory", completed: false, progress: 25 },
      { id: 7, name: "File Systems", completed: false, progress: 20 },
    ],
  },
  {
    id: "cn",
    name: "Computer Networks",
    description: "Networking Fundamentals",
    icon: FaNetworkWired,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    barColor: "linear-gradient(90deg,#06B6D4,#22D3EE)",
    streak: 3,
    studyHours: 7,
    lastStudied: "2 days ago",
    dailyTarget: "1 Topic / day",
    notes: "TCP vs UDP and the HTTP handshake are frequent whiteboard questions.",
    resources: [
      { id: 1, label: "GeeksforGeeks - CN Tutorial", url: "https://www.geeksforgeeks.org/computer-network-tutorials/" },
    ],
    topics: [
      { id: 1, name: "OSI Model", completed: true, progress: 100 },
      { id: 2, name: "TCP/IP", completed: true, progress: 90 },
      { id: 3, name: "Routing", completed: false, progress: 40 },
      { id: 4, name: "Transport Layer", completed: false, progress: 35 },
      { id: 5, name: "TCP vs UDP", completed: false, progress: 30 },
      { id: 6, name: "HTTP/HTTPS", completed: false, progress: 20 },
      { id: 7, name: "DNS", completed: false, progress: 15 },
    ],
  },
  {
    id: "oops",
    name: "OOPs",
    description: "Object-Oriented Programming",
    icon: FaCubes,
    color: "text-green-400",
    bg: "bg-green-500/10",
    barColor: "linear-gradient(90deg,#22C55E,#4ADE80)",
    streak: 12,
    studyHours: 10,
    lastStudied: "2 days ago",
    dailyTarget: "1 Topic / day",
    notes: "Strong on fundamentals — move on to SOLID principles next.",
    resources: [
      { id: 1, label: "GeeksforGeeks - OOPs Concepts", url: "https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/" },
    ],
    topics: [
      { id: 1, name: "Classes & Objects", completed: true, progress: 100 },
      { id: 2, name: "Inheritance", completed: true, progress: 95 },
      { id: 3, name: "Polymorphism", completed: true, progress: 90 },
      { id: 4, name: "Abstraction", completed: false, progress: 55 },
      { id: 5, name: "SOLID Principles", completed: false, progress: 20 },
    ],
  },
  {
    id: "se",
    name: "Software Engineering",
    description: "SDLC & Best Practices",
    icon: FaLaptopCode,
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
    barColor: "linear-gradient(90deg,#FACC15,#FDE047)",
    streak: 2,
    studyHours: 4,
    lastStudied: "4 days ago",
    dailyTarget: "1 Topic / day",
    notes: "Skim through Agile ceremonies and UML diagram types before HR rounds.",
    resources: [
      { id: 1, label: "GeeksforGeeks - SE Tutorial", url: "https://www.geeksforgeeks.org/software-engineering/" },
    ],
    topics: [
      { id: 1, name: "SDLC", completed: true, progress: 100 },
      { id: 2, name: "Agile Process", completed: true, progress: 80 },
      { id: 3, name: "UML Diagrams", completed: false, progress: 30 },
      { id: 4, name: "Testing", completed: false, progress: 20 },
    ],
  },
  {
    id: "coa",
    name: "Computer Organization",
    description: "Computer Architecture",
    icon: FaMicrochip,
    color: "text-red-400",
    bg: "bg-red-500/10",
    barColor: "linear-gradient(90deg,#EF4444,#F87171)",
    streak: 1,
    studyHours: 3.5,
    lastStudied: "5 days ago",
    dailyTarget: "1 Topic / day",
    notes: "Pipelining and cache mapping techniques need another pass.",
    resources: [
      { id: 1, label: "GeeksforGeeks - COA Tutorial", url: "https://www.geeksforgeeks.org/computer-organization-and-architecture-tutorials/" },
    ],
    topics: [
      { id: 1, name: "Number System", completed: true, progress: 100 },
      { id: 2, name: "CPU Architecture", completed: true, progress: 75 },
      { id: 3, name: "Memory Hierarchy", completed: false, progress: 40 },
      { id: 4, name: "Input/Output Systems", completed: false, progress: 15 },
    ],
  },
];

export default subjectsData;